[tool.poetry]
name = "dapper"
version = "0.1.0"
description = ""
authors = ["Ryad Ammar <mohamed.ammar@mail.mcgill.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
